source 'https://github.com/CocoaPods/Specs.Git'
platform :ios, '7.0'

target :ESports do
    pod 'AFNetworking', '3.1.0'
    pod 'RDVTabBarController'
    pod 'JSONModel'
    pod 'MJRefresh'
    pod 'SDWebImage'
    pod 'TMCache'
    pod 'MBProgressHUD'
    pod 'JDStatusBarNotification'
    pod 'TPKeyboardAvoiding'
    pod 'ReactiveCocoa'
    pod 'QBImagePickerController', '2.6.0'
    pod 'BlocksKit' # ,'~> 2.2.5'
    pod 'CMPopTipView'
    #pod 'SDCycleScrollView'#,'~> 1.64'
    pod 'HMSegmentedControl'
    pod 'FMDB'
    pod 'ActionSheetPicker-3.0', '~> 2.2.0'
    pod 'PNChart'
    pod 'Bugly'
end